server {
    listen 80;
    server_name localhost;

    location / {
        # Замени на IP виртуалки, где будет запущен Web-контейнер
        proxy_pass http://192.168.3.4:5000; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
